[package]
name = "einhyrningsins"
version = "0.2.0"
authors = ["bnewbold <bnewbold@robocracy.org>"]

[dependencies]
nix = "0.7"
getopts = "^0.2"
timer = "0.1"
time = "0.1"
chan = "0.1"
chan-signal = "0.1.7"
slog = "1.0"
slog-term = "1.1"
slog-syslog = "1.0.0-alpha"
json = "*"
rustyline = "1.0"
